# Feature encoding

`Feature encoding` is the process of converting categorical data into a format that can be provided to ML algorithms to do a better job in prediction. 

In [8]:
# example of feature encoding
import numpy as np
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

# define input data
data = [['red'], ['green'], ['blue']]
print(data)
# define one hot encoding
encoder = OneHotEncoder(sparse_output=False)

# transform data
onehot = encoder.fit_transform(data)
print(onehot)

# invert first example
inverted = encoder.inverse_transform(onehot)
print(inverted)








[['red'], ['green'], ['blue']]
[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]
[['red']
 ['green']
 ['blue']]


In [ ]:
# example of feature encoding 2



# define input data
data = [['red'], ['green'], ['blue']]
print(data)

# create a one hot encoding

encoder = OneHotEncoder(sparse_output=False)
onehot = encoder.fit_transform(data)
print(onehot)