# Feature encoding

`Feature encoding` mai categorical data ko numerical data mai convert karna hota hai. Categorical data ko numerical data mai convert karne ke liye different techniques use ki jati hain jese `Label Encoding`, `One Hot Encoding`, `Target Encoding` etc.

# why we need feature encoding?

Machine learning models only understand numerical data. Categorical data ko numerical data mai convert karne ke liye feature encoding ki zarurat hoti hai. or computer numerical data ko samajh sakta hai.

1. mostly ML ke algorithms categorical data ko support nahi karte hain. is liye categorical data ko numerical data mai convert karna zaruri hota hai.
2. efficient computation: numerical data ko process karna easy hota hai as compare to categorical data.

3. Feature representation: numerical data ko visualize karna easy hota hai as compare to categorical data.

4. Support unseen categories: agar model ko unseen categories se face karna hota hai to model categorical data ko numerical data mai convert karne se is problem se bach sakta hai.


In [38]:
# Import libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

# load dataset

data = sns.load_dataset('tips')
data.head()


total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [39]:
data['day'].value_counts()

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64

---
 # Types of Feature Encoding



# 1. Label Encoding

`Label Encoding` mai categorical data ko numerical data mai convert karte hain. Is technique mai har unique category ko unique number assign kiya jata hai. For example agar humare pass 3 unique categories hain jese `A`, `B` and `C` to hum in categories ko 1, 2 and 3 assign kar sakte hain.

In [41]:
# label encoder


from sklearn.preprocessing import LabelEncoder, OneHotEncoder, OrdinalEncoder

le=LabelEncoder()

data['day']=le.fit_transform(data['day'])
data=data['day']
data.head()





0    2
1    2
2    2
3    2
4    2
Name: day, dtype: int64


# 2. One Hot Encoding

`One Hot Encoding` mai categorical data ko binary form mai convert kiya jata hai. Is technique mai har unique category ko ek new column mai convert kiya jata hai. For example agar humare pass 3 unique categories hain jese `A`, `B` and `C` to hum in categories ko 3 new columns mai convert kar sakte hain. Agar koi row `A` category mai belong karta hai to us row ke `A` column mai 1 assign kiya jata hai aur `B` and `C` column mai 0 assign kiya jata hai.


In [36]:
from sklearn.preprocessing import OneHotEncoder

# define input data
data = [['red'], ['green'], ['blue']]
print("Original data:", data)

# create a one hot encoding
encoder = OneHotEncoder(sparse_output=False)
onehot = encoder.fit_transform(data)
print("One hot encoded data:\n", onehot)

Original data: [['red'], ['green'], ['blue']]
One hot encoded data:
 [[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]



# 3. Ordinal Encoding

`Ordinal Encoding` mai categorical data ko numerical data mai convert kiya jata hai. Is technique mai categories ko order mai convert kiya jata hai. For example agar humare pass 3 unique categories hain jese `A`, `B` and `C` to hum in categories ko 1, 2 and 3 assign kar sakte hain. Is technique mai categories ko order mai convert kiya jata hai jese `A` ko 1, `B` ko 2 and `C` ko 3 assign kiya jata hai.

In [45]:
# Ensure data is a DataFrame and contains the 'day' column
data = sns.load_dataset('tips')
# data['day'] = le.fit_transform(data['day'])
data['day'].value_counts()

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64

In [52]:
# Ordinal encoding the day column using specific order

# from sklearn.preprocessing import OrdinalEncoder
import pandas as pd

# Reload the original dataset to get the 'day' column in its original string format
data = sns.load_dataset('tips')

oe = OrdinalEncoder(categories=[['Thur', 'Fri', 'Sat', 'Sun']])
data['day'] = oe.fit_transform(data[['day']])

data.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  3.0  Dinner     2
1       10.34  1.66    Male     No  3.0  Dinner     3
2       21.01  3.50    Male     No  3.0  Dinner     3
3       23.68  3.31    Male     No  3.0  Dinner     2
4       24.59  3.61  Female     No  3.0  Dinner     4


# 4. Binary Encoding

`Binary Encoding` mai categorical data ko binary form mai convert kiya jata hai. Is technique mai categories ko binary form mai convert kiya jata hai. For example agar humare pass 3 unique categories hain jese `A`, `B` and `C` to hum in categories ko binary form mai convert kar sakte hain. Is technique mai categories ko binary form mai convert kiya jata hai jese `A` ko 001, `B` ko 010 and `C` ko 100 assign kiya jata hai.

In [5]:
from sklearn.preprocessing import LabelBinarizer

# define input data
data = ['red', 'green', 'blue']
print("Original data:", data)

# create a binary encoder
encoder = LabelBinarizer()
binary_encoded = encoder.fit_transform(data)
print("Binary encoded data:\n", binary_encoded)

Original data: ['red', 'green', 'blue']
Binary encoded data:
 [[0 0 1]
 [0 1 0]
 [1 0 0]]



# 5. Frequency on count Encoding

`Frequency on count Encoding` mai categorical data ko numerical data mai convert kiya jata hai. Is technique mai categories ko unki frequency ke hisab se convert kiya jata hai. For example agar humare pass 3 unique categories hain jese `A`, `B` and `C` to hum in categories ko unki frequency ke hisab se convert kar sakte hain. Is technique mai categories ko unki frequency ke hisab se convert kiya jata hai jese `A` ko 1, `B` ko 2 and `C` ko 3 assign kiya jata hai.

In [ ]:
import pandas as pd

# define input data
data = pd.Series(['red', 'green', 'blue', 'green', 'blue', 'blue'])
print("Original data:\n", data)

# create a frequency encoding
frequency_encoded = data.map(data.value_counts())
print("Frequency encoded data:\n", frequency_encoded)

In [8]:
# example of feature encoding
import numpy as np
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

# define input data
data = [['red'], ['green'], ['blue']]
print(data)
# define one hot encoding
encoder = OneHotEncoder(sparse_output=False)

# transform data
onehot = encoder.fit_transform(data)
print(onehot)

# invert first example
inverted = encoder.inverse_transform(onehot)
print(inverted)








[['red'], ['green'], ['blue']]
[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]
[['red']
 ['green']
 ['blue']]


In [9]:
# example of feature encoding 2



# define input data
data = [['red'], ['green'], ['blue']]
print(data)

# create a one hot encoding

encoder = OneHotEncoder(sparse_output=False)
onehot = encoder.fit_transform(data)
print(onehot)

[['red'], ['green'], ['blue']]
[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]


In [10]:
# types of feature encoding
# integer encoding
# one hot encoding
# binary encoding
# label encoding
# target encoding
# frequency encoding
# mean encoding
# weight of evidence encoding

# integer encoding

# define input data
data = ['red', 'green', 'blue', 'red']
print(data)

# define mapping of unique values to integers
mapping = {'red': 0, 'green': 1, 'blue': 2}

# convert string to integer
integer_data = [mapping[value] for value in data]
print(integer_data)

['red', 'green', 'blue', 'red']
[0, 1, 2, 0]


In [9]:
import numpy as np
from sklearn.preprocessing import OneHotEncoder

# define input data
data = [['red'], ['green'], ['blue']]
print(data)

# create a one hot encoding
encoder = OneHotEncoder(sparse_output=False)
onehot = encoder.fit_transform(data)
print(onehot)

[['red'], ['green'], ['blue']]
[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]


In [10]:

# invert first example
inverted = encoder.inverse_transform(onehot)
print(inverted)



[['red']
 ['green']
 ['blue']]


In [11]:

# binary encoding

# define larger input data
data = [['red', 1], ['green', 4], ['blue', 2]]
print(data)

# convert string input to integer
mapping = {'red': 0, 'green': 1, 'blue': 2}
for i in range(len(data)):
    data[i][0] = mapping[data[i][0]]
print(data)

# convert integer to binary
from sklearn.preprocessing import OneHotEncoder
import numpy as np

data = np.array(data)
print(data)




[['red', 1], ['green', 4], ['blue', 2]]
[[0, 1], [1, 4], [2, 2]]
[[0 1]
 [1 4]
 [2 2]]


In [12]:

# label encoding

# define input data
data = ['red', 'green', 'blue', 'red']
print(data)

# import label encoder
from sklearn.preprocessing import LabelEncoder

# create label encoder
label_encoder = LabelEncoder()

# fit and transform data
integer_encoded = label_encoder.fit_transform(data)
print(integer_encoded)



['red', 'green', 'blue', 'red']
[2 1 0 2]


In [1]:
# target encoding

# define input data
data = ['red', 'green', 'blue', 'red']
print(data)

# define mapping of unique values to target encoding
mapping = {'red': 0.1, 'green': 0.2, 'blue': 0.3}

# convert string input to target encoding
target_data = [mapping[value] for value in data]
print(target_data)




['red', 'green', 'blue', 'red']
[0.1, 0.2, 0.3, 0.1]


In [ ]:
# target encoding

# define input data
data = ['red', 'green', 'blue', 'red']
print(data)

# define mapping of unique values to target encoding
mapping = {'red': 0.1, 'green': 0.2, 'blue': 0.3}

# convert string input to target encoding
target_data = [mapping[value] for value in data]
print(target_data)




In [ ]:
# target encoding

# define input data
data = ['red', 'green', 'blue', 'red']
print(data)

# define mapping of unique values to target encoding
mapping = {'red': 0.1, 'green': 0.2, 'blue': 0.3}

# convert string input to target encoding
target_data = [mapping[value] for value in data]
print(target_data)




In [ ]:
# target encoding

# define input data
data = ['red', 'green', 'blue', 'red']
print(data)

# define mapping of unique values to target encoding
mapping = {'red': 0.1, 'green': 0.2, 'blue': 0.3}

# convert string input to target encoding
target_data = [mapping[value] for value in data]
print(target_data)




In [ ]:
# target encoding

# define input data
data = ['red', 'green', 'blue', 'red']
print(data)

# define mapping of unique values to target encoding
mapping = {'red': 0.1, 'green': 0.2, 'blue': 0.3}

# convert string input to target encoding
target_data = [mapping[value] for value in data]
print(target_data)




In [ ]:
# target encoding

# define input data
data = ['red', 'green', 'blue', 'red']
print(data)

# define mapping of unique values to target encoding
mapping = {'red': 0.1, 'green': 0.2, 'blue': 0.3}

# convert string input to target encoding
target_data = [mapping[value] for value in data]
print(target_data)


