# Feature encoding

`Feature encoding` mai categorical data ko numerical data mai convert karna hota hai. Categorical data ko numerical data mai convert karne ke liye different techniques use ki jati hain jese `Label Encoding`, `One Hot Encoding`, `Target Encoding` etc.

# why we need feature encoding?

Machine learning models only understand numerical data. Categorical data ko numerical data mai convert karne ke liye feature encoding ki zarurat hoti hai. or computer numerical data ko samajh sakta hai.

1. mostly ML ke algorithms categorical data ko support nahi karte hain. is liye categorical data ko numerical data mai convert karna zaruri hota hai.
2. efficient computation: numerical data ko process karna easy hota hai as compare to categorical data.

3. Feature representation: numerical data ko visualize karna easy hota hai as compare to categorical data.

4. Support unseen categories: agar model ko unseen categories se face karna hota hai to model categorical data ko numerical data mai convert karne se is problem se bach sakta hai.


---
 # Types of Feature Encoding



# 1. Label Encoding

`Label Encoding` mai categorical data ko numerical data mai convert karte hain. Is technique mai har unique category ko unique number assign kiya jata hai. For example agar humare pass 3 unique categories hain jese `A`, `B` and `C` to hum in categories ko 1, 2 and 3 assign kar sakte hain.

In [1]:
from sklearn.preprocessing import LabelEncoder

# define input data
data = ['red', 'green', 'blue']
print("Original data:", data)

# create a label encoder
encoder = LabelEncoder()
labels = encoder.fit_transform(data)
print("Label encoded data:", labels)



Original data: ['red', 'green', 'blue']
Label encoded data: [2 1 0]



# 2. One Hot Encoding

`One Hot Encoding` mai categorical data ko binary form mai convert kiya jata hai. Is technique mai har unique category ko ek new column mai convert kiya jata hai. For example agar humare pass 3 unique categories hain jese `A`, `B` and `C` to hum in categories ko 3 new columns mai convert kar sakte hain. Agar koi row `A` category mai belong karta hai to us row ke `A` column mai 1 assign kiya jata hai aur `B` and `C` column mai 0 assign kiya jata hai.


In [3]:
from sklearn.preprocessing import OneHotEncoder

# define input data
data = [['red'], ['green'], ['blue']]
print("Original data:", data)

# create a one hot encoding
encoder = OneHotEncoder(sparse_output=False)
onehot = encoder.fit_transform(data)
print("One hot encoded data:\n", onehot)

Original data: [['red'], ['green'], ['blue']]
One hot encoded data:
 [[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]



# 3. Ordinal Encoding

`Ordinal Encoding` mai categorical data ko numerical data mai convert kiya jata hai. Is technique mai categories ko order mai convert kiya jata hai. For example agar humare pass 3 unique categories hain jese `A`, `B` and `C` to hum in categories ko 1, 2 and 3 assign kar sakte hain. Is technique mai categories ko order mai convert kiya jata hai jese `A` ko 1, `B` ko 2 and `C` ko 3 assign kiya jata hai.

In [4]:
from sklearn.preprocessing import OrdinalEncoder

# define input data
data = [['low'], ['medium'], ['high']]
print("Original data:", data)

# create an ordinal encoder
encoder = OrdinalEncoder()
ordinal_encoded = encoder.fit_transform(data)
print("Ordinal encoded data:\n", ordinal_encoded)

Original data: [['low'], ['medium'], ['high']]
Ordinal encoded data:
 [[1.]
 [2.]
 [0.]]



# 4. Binary Encoding

`Binary Encoding` mai categorical data ko binary form mai convert kiya jata hai. Is technique mai categories ko binary form mai convert kiya jata hai. For example agar humare pass 3 unique categories hain jese `A`, `B` and `C` to hum in categories ko binary form mai convert kar sakte hain. Is technique mai categories ko binary form mai convert kiya jata hai jese `A` ko 001, `B` ko 010 and `C` ko 100 assign kiya jata hai.


# 5. Frequency on count Encoding

`Frequency on count Encoding` mai categorical data ko numerical data mai convert kiya jata hai. Is technique mai categories ko unki frequency ke hisab se convert kiya jata hai. For example agar humare pass 3 unique categories hain jese `A`, `B` and `C` to hum in categories ko unki frequency ke hisab se convert kar sakte hain. Is technique mai categories ko unki frequency ke hisab se convert kiya jata hai jese `A` ko 1, `B` ko 2 and `C` ko 3 assign kiya jata hai.

In [8]:
# example of feature encoding
import numpy as np
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

# define input data
data = [['red'], ['green'], ['blue']]
print(data)
# define one hot encoding
encoder = OneHotEncoder(sparse_output=False)

# transform data
onehot = encoder.fit_transform(data)
print(onehot)

# invert first example
inverted = encoder.inverse_transform(onehot)
print(inverted)








[['red'], ['green'], ['blue']]
[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]
[['red']
 ['green']
 ['blue']]


In [9]:
# example of feature encoding 2



# define input data
data = [['red'], ['green'], ['blue']]
print(data)

# create a one hot encoding

encoder = OneHotEncoder(sparse_output=False)
onehot = encoder.fit_transform(data)
print(onehot)

[['red'], ['green'], ['blue']]
[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]


In [10]:
# types of feature encoding
# integer encoding
# one hot encoding
# binary encoding
# label encoding
# target encoding
# frequency encoding
# mean encoding
# weight of evidence encoding

# integer encoding

# define input data
data = ['red', 'green', 'blue', 'red']
print(data)

# define mapping of unique values to integers
mapping = {'red': 0, 'green': 1, 'blue': 2}

# convert string to integer
integer_data = [mapping[value] for value in data]
print(integer_data)

['red', 'green', 'blue', 'red']
[0, 1, 2, 0]


In [9]:
import numpy as np
from sklearn.preprocessing import OneHotEncoder

# define input data
data = [['red'], ['green'], ['blue']]
print(data)

# create a one hot encoding
encoder = OneHotEncoder(sparse_output=False)
onehot = encoder.fit_transform(data)
print(onehot)

[['red'], ['green'], ['blue']]
[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]


In [10]:

# invert first example
inverted = encoder.inverse_transform(onehot)
print(inverted)



[['red']
 ['green']
 ['blue']]


In [11]:

# binary encoding

# define larger input data
data = [['red', 1], ['green', 4], ['blue', 2]]
print(data)

# convert string input to integer
mapping = {'red': 0, 'green': 1, 'blue': 2}
for i in range(len(data)):
    data[i][0] = mapping[data[i][0]]
print(data)

# convert integer to binary
from sklearn.preprocessing import OneHotEncoder
import numpy as np

data = np.array(data)
print(data)




[['red', 1], ['green', 4], ['blue', 2]]
[[0, 1], [1, 4], [2, 2]]
[[0 1]
 [1 4]
 [2 2]]


In [12]:

# label encoding

# define input data
data = ['red', 'green', 'blue', 'red']
print(data)

# import label encoder
from sklearn.preprocessing import LabelEncoder

# create label encoder
label_encoder = LabelEncoder()

# fit and transform data
integer_encoded = label_encoder.fit_transform(data)
print(integer_encoded)



['red', 'green', 'blue', 'red']
[2 1 0 2]


In [1]:
# target encoding

# define input data
data = ['red', 'green', 'blue', 'red']
print(data)

# define mapping of unique values to target encoding
mapping = {'red': 0.1, 'green': 0.2, 'blue': 0.3}

# convert string input to target encoding
target_data = [mapping[value] for value in data]
print(target_data)




['red', 'green', 'blue', 'red']
[0.1, 0.2, 0.3, 0.1]


In [ ]:
# target encoding

# define input data
data = ['red', 'green', 'blue', 'red']
print(data)

# define mapping of unique values to target encoding
mapping = {'red': 0.1, 'green': 0.2, 'blue': 0.3}

# convert string input to target encoding
target_data = [mapping[value] for value in data]
print(target_data)




In [ ]:
# target encoding

# define input data
data = ['red', 'green', 'blue', 'red']
print(data)

# define mapping of unique values to target encoding
mapping = {'red': 0.1, 'green': 0.2, 'blue': 0.3}

# convert string input to target encoding
target_data = [mapping[value] for value in data]
print(target_data)




In [ ]:
# target encoding

# define input data
data = ['red', 'green', 'blue', 'red']
print(data)

# define mapping of unique values to target encoding
mapping = {'red': 0.1, 'green': 0.2, 'blue': 0.3}

# convert string input to target encoding
target_data = [mapping[value] for value in data]
print(target_data)




In [ ]:
# target encoding

# define input data
data = ['red', 'green', 'blue', 'red']
print(data)

# define mapping of unique values to target encoding
mapping = {'red': 0.1, 'green': 0.2, 'blue': 0.3}

# convert string input to target encoding
target_data = [mapping[value] for value in data]
print(target_data)




In [ ]:
# target encoding

# define input data
data = ['red', 'green', 'blue', 'red']
print(data)

# define mapping of unique values to target encoding
mapping = {'red': 0.1, 'green': 0.2, 'blue': 0.3}

# convert string input to target encoding
target_data = [mapping[value] for value in data]
print(target_data)


