# Feature encoding

`Feature encoding` is the process of converting categorical data into a format that can be provided to ML algorithms to do a better job in prediction. 

In [8]:
# example of feature encoding
import numpy as np
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

# define input data
data = [['red'], ['green'], ['blue']]
print(data)
# define one hot encoding
encoder = OneHotEncoder(sparse_output=False)

# transform data
onehot = encoder.fit_transform(data)
print(onehot)

# invert first example
inverted = encoder.inverse_transform(onehot)
print(inverted)








[['red'], ['green'], ['blue']]
[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]
[['red']
 ['green']
 ['blue']]


In [9]:
# example of feature encoding 2



# define input data
data = [['red'], ['green'], ['blue']]
print(data)

# create a one hot encoding

encoder = OneHotEncoder(sparse_output=False)
onehot = encoder.fit_transform(data)
print(onehot)

[['red'], ['green'], ['blue']]
[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]


In [10]:
# types of feature encoding
# integer encoding
# one hot encoding
# binary encoding
# label encoding
# target encoding
# frequency encoding
# mean encoding
# weight of evidence encoding

# integer encoding

# define input data
data = ['red', 'green', 'blue', 'red']
print(data)

# define mapping of unique values to integers
mapping = {'red': 0, 'green': 1, 'blue': 2}

# convert string to integer
integer_data = [mapping[value] for value in data]
print(integer_data)

['red', 'green', 'blue', 'red']
[0, 1, 2, 0]


In [1]:

# one hot encoding
# define input data

data = [['red'], ['green'], ['blue']]
print(data)


[['red'], ['green'], ['blue']]
